### ISSUE TITLE
Full text for "Semantics and Pragmatics" not noticed

### ISSUE THREAD

**Issue by a3nm** [dissemin/dissemin#153] opened 2015-11-08 00:34 UTC
The following paper http://public.dissem.in/paper/66358/ indicates "Full text: Unavailable " but the full text is in open access on the journal's page http://semprag.org/article/view/sp.7.11

**Comment by wetneb** [comment] 2015-11-08 08:17
Full texts from publishers are never noticed unless they are open access publishers (registered in DOAJ). This is because detecting hybrid open access is complicated. The metadata from CrossRef does not indicate whether the paper is available or not. One option would be to scrape with Zotero (issue #90) but it does not look straightforward. Any ideas welcome! And that's something people can work on with no knowledge of our code. (Just try to answer the following question: Given a DOI, how do I check whether the paper is paywalled or not?)

**Comment by a3nm** [comment] 2015-11-08 11:04
At least, one option would be to have a "re-scan" button next to the field that says the article is not available, which would use Zotero to scrape the page at that moment.

**Comment by wetneb** [comment] 2016-07-03 06:23
Closing this as it is a duplicate of #236.

**Closed by wetneb** 2016-07-03 06:23 UTC
Labels: back end, enhancement, help wanted
