### ISSUE TITLE
Missing papers in dissem.in (available through BASE)

### ISSUE THREAD

**Issue by BibliotekaITNSANU** [dissemin/dissemin#500] opened 2017-11-21 09:33 UTC
1. The paper 
Dragana Jugović, Miloš Milović, Valentin N. Ivanovski, Max AvdeevORCID, Robert DominkoORCID, Bojan Jokić, Dragan Uskoković
Structural study of monoclinic Li2FeSiO4 by X-ray diffraction and Mössbauer spectroscopy
Elsevier, Journal of Power Sources, (265), p. 75-80.
is available in an open repository, but the information is missing in dissem.in. 
It can be found in BASE:
https://www.base-search.net/Record/497a220858f3eb60187a0e722bc7d10ccff840ba04a5293f5968ec2b60b73ebc/ 

2. The paper:
Miloš Milović, Dragana Jugović, Nikola Cvjetićanin, Dragan UskokovićORCID, Aleksandar S. Milošević, Zoran S. Popović, Filip R. Vukajlović
Crystal structure analysis and first principle investigation of F doping in LiFePO4
Elsevier, Journal of Power Sources, (241), p. 70-79.
is available in an open repository, but the information is missing in dissem.in. 
It can be found in BASE:
https://www.base-search.net/Record/87ac1f279f55c32ac1c1d23c35d7e9ff86739aba38f0064c8679bb324fc337c7/ 

3. The paper:
Dragana Jugović, Miodrag Mitrić, Miloš Milović, Bojan Jokić, Marija Vukomanović, Danilo Suvorov, Dragan Uskoković
Properties of quenched LiFePO4/C powder obtained via cellulose matrix-assisted method
Elsevier, Powder Technology, (246), p. 539-544.
is available in an open repository, but the information is missing in dissem.in. 
It can be found in BASE:
https://www.base-search.net/Record/1f29ab3d19c895b855440887ce1e03f2b0c4b13f8770a4259ee01e60dbda9142/ 

4. The paper:
 Dragana Jugović, Miodrag Mitrić, Maja Kuzmanović, Nikola Cvjetićanin, Srečo Škapin, Božidar Cekić, Valentin Ivanovski, Dragan Uskoković
Preparation of LiFePO4/C composites by co-precipitation in molten stearic acid
Elsevier, Journal of Power Sources, 10(196), p. 4613-4618.
https://www.base-search.net/Record/17010a8686f3ac28729e8288813618aceed50a1fe861364810974d19bae2ecd1/

**Comment by cristiansigloxxi** [comment] 2018-03-23 14:19
Hi, we have the same problem.

A lot of papers are missing in dissem.in
BASE URL: https://www.base-search.net/Search/Results?q=dccoll:ftunivnmdpfceys

**Comment by wetneb** [comment] 2018-03-23 14:52
@cristiansigloxxi yes, we are aware of the issue - unfortunately, none of the volunteers who run the platform currently have time to work on this.

**Comment by a3nm** [comment] 2018-10-24 14:12
Another case that was reported is this article https://www.base-search.net/Record/fe7344b289a368fea21d3e8614d4f9edeb46844f5b09509993bf170d6392500a/  that cannot be found when searching for Iris Hanique.

**Comment by wetneb** [comment] 2019-02-18 08:44
closing as duplicate of #431.

**Closed by wetneb** 2019-02-18 08:44 UTC
Labels: back end, duplicate
