### ISSUE TITLE
Repository descriptions are not localized

### ISSUE THREAD

**Issue by a3nm** [dissemin/dissemin#444] opened 2017-08-29 17:04 UTC
On e.g. https://dissem.in/deposit_paper/92821051/?type=pdfversion the descriptions of repositories are not localized, e.g. "Zenodo is a general-purpose open repository hosted by CERN. If the document does not have a DOI yet, Zenodo will create one."

This is not easy to fix because apparently these repositories are retrieved from the database (`get_all_repositories_and_protocols` in `deposit/views.py`) so the strings to localize do not occur in the code. I'm not sure what's the proper way to fix this... I guess this would require changing the database schema to have descriptions in multiple languages, and change the code to retrieve the right one depending on the current language...

**Comment by wetneb** [comment] 2017-08-29 17:12
Closing as a duplicate of #364.

**Closed by wetneb** 2017-08-29 17:12 UTC

**Comment by a3nm** [comment] 2017-08-29 17:42
Oops, sorry, hadn't thought someone had already complained about this. :-P
