### ISSUE TITLE
Accessibility of names for new ORCID profiles

### ISSUE THREAD

**Issue by a3nm** [dissemin/dissemin#745] opened 2019-05-02 13:53 UTC
We hit the same issue as #721 but for an ORCID proflie where the name is (and always has been) public. Steps to reproduce:

- Create an ORCID profile with no publications (and with no publications known to Dissemin). We used https://orcid.org/0000-0001-7449-8161
- Make sure that the visibility of the name of this profile is public
- Log into Dissemin using this ORCID
- Go to "my profile", hit the ugly error page as in #721 

One thing that seems weird: in Authentication and Authorization › Users, a user "remi46" has been created, and in Papers › Researchers, a researcher "Rémi Dupré" has been created, but the "user" field of the researcher object does not point to "remi46", so there is apparently no link between the logged in user and the Researcher object with the information about the ORCID profile. So could this be a problem where this doesn't work if the Researcher object needed to be created because it did not previously exist?

Flagging this as important as it makes the site look broken to many new users.

**Comment by Phyks** [comment] 2019-05-07 13:01
This is actually precisely a duplicate of #721 I think.

First, could you check the uglyness of the error page? On `master` branch locally, using https://sandbox.orcid.org/0000-0002-7013-2493, I have a styled error page now:

![Capture d’écran 2019-05-07 à 15 00 47](https://user-images.githubusercontent.com/3856586/57301306-ffe5ae00-70d8-11e9-96ae-57885b5b3638.png)

I'll have a look at the true underlying error.

**Closed** 2019-05-12 10:28 UTC
Labels: important, matching PR

**Comment by a3nm** [comment] 2019-05-13 12:52
Just checked and this is indeed fixed for the user of profile https://orcid.org/0000-0001-7449-8161. Great! :)
