### ISSUE TITLE
reason: Undefined

### ISSUE THREAD

**Issue by cpitclaudel** [dissemin/dissemin#330] opened 2016-11-26 16:06 UTC
Both messages in this screenshot look fishy:

![image](https://cloud.githubusercontent.com/assets/8181630/20641539/44f1da30-b3c8-11e6-9ff8-90b4cb013127.png)

My ORCID profile does have papers, and reason: undefined is not very informative :)

**Comment by wetneb** [comment] 2016-11-26 16:24
thanks, it's quite ugly indeed. By the way, are we talking about https://orcid.org/0000-0002-1900-3901? If I'm not mistaken, this profile does not have any name (or at least no public name). I think the profile should be rejected in the first place (#327).

**Comment by cpitclaudel** [comment] 2016-11-26 16:32
Yeah. Wouldn't it be helpful if orcid.org had a clear way to make a profile public?

**Comment by cpitclaudel** [comment] 2016-11-26 16:36
Should be fixed now.  Don't ask me why ORCID's privacy settings widget is operated by a third party that uses a tracking cookie.

**Comment by wetneb** [comment] 2016-11-26 16:39
thanks! yeah their interface is quite confusing.

**Comment by wetneb** [comment] 2017-05-12 16:09
Note: there is still a problem with papers not being imported from the ORCID profile for some reason.

**Comment by Phyks** [comment] 2019-01-25 15:23
Now that #327 is merged, the first root cause of this issue should be fixed, I guess. Looking at the Dissem.in profile matching the ORCID ID in https://github.com/dissemin/dissemin/issues/330#issuecomment-263072163, it seems all the (public) papers from ORCID are imported in Dissemin.

Is there still an issue here? Or should it be closed?

**Comment by wetneb** [comment] 2019-02-03 14:45
The only outstanding issue here is that the messages should be readable and their wording should be improved, I think.

**Closed** 2019-02-18 10:23 UTC
Labels: important, orcid
