### ISSUE TITLE
English in the FAQ page

### ISSUE THREAD

**Issue by a3nm** [dissemin/dissemin#743] opened 2019-05-02 13:14 UTC
There is some English left in the French version of the FAQ (look for " the " in https://dissem.in/faq with a browser configured in French): "Please first check whether the paper is available in one of our sources. If it is not, Dissemin cannot harvest it, and you should report the problem to the source where it should appear. Note that it can take up to a couple of months for our primary sources to discover your latest papers and for Dissemin to harvest it."

The corresponding translation exists in translatewiki (and I have just marked it as verified).

Is this normal? How can we refresh the translations to see whether this fixes the issue?

**Comment by Phyks** [comment] 2019-05-02 13:19
We updated the translations in multiple places recently (within the code, source translations I mean) and there is a bit of English scattered everywhere at the moment indeed (same with "Advanced search on the front page etc).

TranslateWiki updates might not have been reflected online yet. I'll let @wetneb comment on this :)

**Comment by wetneb** [comment] 2019-05-02 15:54
Translations are periodically pushed by Translatewiki and we need to compile them when deploying (see https://dissemin.readthedocs.io/en/latest/localization.html). It is possible that I forget to compile them when deploying (and reloading apache afterwards) - I have done it recently but just to be sure I have just recompiled them again.

**Comment by Phyks** [comment] 2019-07-15 13:27
I've just done a full deploy of Dissemin including compilation of translations and this is still happening https://dissem.in/faq#missing-paper.

It seems the strings in English are annotated with a `#, fuzzy, python-format` comment in the translation files. What does it mean? See https://github.com/dissemin/dissemin/blob/master/locale/fr/LC_MESSAGES/django.po#L1891-L1894 and https://github.com/dissemin/dissemin/blob/master/locale/fr/LC_MESSAGES/django.po#L1908-L1911.

**Comment by wetneb** [comment] 2019-07-15 14:34
"fuzzy" means these translations were inferred from others because the source strings were close (I think). I am not sure but I think this means these translations are ignored by Django - they are only suggested meant to be suggested to translators as a possible string to start from.

**Comment by Phyks** [comment] 2019-07-15 14:38
Makes sense and confirmed by http://share-experiences.com/blog/what-fuzzy-means-python-django-gettext/ indeed.

So I guess @a3nm you should review and tag them as being correct in Translatewiki to remove English from the FAQ page.

We can probably close this one then.

**Closed by Phyks** 2019-07-15 14:38 UTC
Labels: dissem.in, front end, localization, question

**Comment by a3nm** [comment] 2019-08-08 14:42
Sorry for getting back to this so late. I have reviewed all the translations of Dissemin from English to French that I could, let's see whether it solves the problem.

I'm not sure about what's the right workflow to review translations -- chatting with Nemo_bis about that.

**Comment by nemobis** [comment] 2019-08-09 04:27
> I have reviewed all the translations of Dissemin from English to French that I could, let's see whether it solves the problem.

I'm not sure what reviewing has to do with this issue, which seems to be just about untranslated (outdated) messages. To find translations which need updates you can for instance go to http://translatewiki.net/wiki/translating:Dissemin , click the translate button, click the "outdated" tab. You should reach
https://translatewiki.net/w/i.php?title=Special:Translate&group=dissemin&language=fr&filter=fuzzy&action=translate

If some translation is already made and confirmed up to date but not exported as such in the most recent commit, that would be a bug.

More in general marking strings as "fuzzy" is a way to increase the quality of translations: translators are forced to re-translate something, but they avoid surprises in how their translations are used (assuming the message documentation is accurate). If you tell me which part of all this is the most confusing and where you would have looked for information, I'll try to document it better, maybe at https://translatewiki.net/wiki/FAQ#Old_or_obsolete_messages or https://translatewiki.net/wiki/Translating:Localisation_for_developers#Message_documentation .

**Comment by a3nm** [comment] 2019-08-09 08:24
OK, I guess I was just confused by @Phyks's point that I should review translations, then. I thought the reason why translations were not being exported was that they had not been reviewed.

That said, when going to https://translatewiki.net/w/i.php?title=Special:Translate&group=dissemin&language=fr&filter=fuzzy&action=translate I see a big message "Nothing to translate", but currently there are still some messages showing in English on the interface: go to https://dissem.in/faq with the interface in French, and search for "In most cases".

It's possible that while reviewing yesterday I also updated the corresponding translation and that the new translations just need to be deployed (?), so maybe we should wait for a few days.

**Comment by Phyks** [comment] 2019-08-10 11:26
> I'm not sure what reviewing has to do with this issue, which seems to be just about untranslated (outdated) messages.

I'm a bit lost here. The untranslated strings were marked as "fuzzy". See https://github.com/dissemin/dissemin/blob/master/locale/fr/LC_MESSAGES/django.po#L1908-L1911 for instance which has a translation but is marked as being "fuzzy".

It seems "fuzzy" translations are not exported in the Django translation files. I'm not sure what "fuzzy" means in terms of translatewiki UX though.

**Comment by nemobis** [comment] 2019-08-26 06:28
Lucas Verney, 10/08/19 14:26:
> It seems "fuzzy" translations are not exported in the Django translation 
> files. I'm not sure what "fuzzy" means in terms of translatewiki UX though.

It's explained in
https://translatewiki.net/wiki/FAQ#Old_or_obsolete_messages
https://www.mediawiki.org/wiki/Help:Extension:Translate/Glossary
