### ISSUE TITLE
Refreshing ORCID automatically

### ISSUE THREAD

**Issue by a3nm** [dissemin/dissemin#480] opened 2017-10-27 09:00 UTC
When a user changes their ORCID profile, Dissemin doesn't notice the change automatically: the user has to go to their profile and click "Refresh publications". It would be better if Dissemin could do so automatically from time to time. To keep the load down, it would probably better to do this in priority for users who have recently logged in.

**Comment by wetneb** [comment] 2017-11-13 13:21
Closing as duplicate of #448.

**Closed by wetneb** 2017-11-13 13:21 UTC
Labels: back end, enhancement, orcid
